# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Guppi < Formula
  desc "TUI for managing multiple git repositories"
  homepage "https://github.com/Quietscher/guppi"
  version "1.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Quietscher/guppi/releases/download/1.3.2/guppi_1.3.2_darwin_amd64.tar.gz"
      sha256 "4575f10e44203dbe41c1a79726c1da497410a916f191131884af367297c99145"

      def install
        bin.install "guppi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Quietscher/guppi/releases/download/1.3.2/guppi_1.3.2_darwin_arm64.tar.gz"
      sha256 "0857b1c90f7f57186d9fd0fae2c0acfb6ca226b9e0d898c574ed281325c52955"

      def install
        bin.install "guppi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Quietscher/guppi/releases/download/1.3.2/guppi_1.3.2_linux_amd64.tar.gz"
      sha256 "8a7c85e8689f36ba52532a2aa498cf5a40d52aac36ee51992e3f22852d11ccac"
      def install
        bin.install "guppi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Quietscher/guppi/releases/download/1.3.2/guppi_1.3.2_linux_arm64.tar.gz"
      sha256 "aa25a15bf8114c9bb852472577d8a8df4e2664d9ef84892425d01977d36ccbd1"
      def install
        bin.install "guppi"
      end
    end
  end

  test do
    system "#{bin}/guppi", "--version"
  end
end
