# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Guppi < Formula
  desc "TUI for managing multiple git repositories"
  homepage "https://github.com/Quietscher/guppi"
  version "1.5.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Quietscher/guppi/releases/download/1.5.5/guppi_1.5.5_darwin_amd64.tar.gz"
      sha256 "6b88e9df23aba5a42469c619cf495d7ef25fe080b3176acb7a18e76db2189f2f"

      def install
        bin.install "guppi"
        bin.install_symlink "guppi" => "gpi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Quietscher/guppi/releases/download/1.5.5/guppi_1.5.5_darwin_arm64.tar.gz"
      sha256 "77cf31e2d675ce114ff60321613e3ad532131a4ed0bd178336850f6ed9909464"

      def install
        bin.install "guppi"
        bin.install_symlink "guppi" => "gpi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Quietscher/guppi/releases/download/1.5.5/guppi_1.5.5_linux_amd64.tar.gz"
      sha256 "3c78ac656faa949f2dd8fc71d406008450f36039c4908dd67f6a2f0e313a9c00"
      def install
        bin.install "guppi"
        bin.install_symlink "guppi" => "gpi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Quietscher/guppi/releases/download/1.5.5/guppi_1.5.5_linux_arm64.tar.gz"
      sha256 "ba0cc38142f7e8fafefd7163da19a11aa04d4c89b164f3646d9ed5bbe604c0e9"
      def install
        bin.install "guppi"
        bin.install_symlink "guppi" => "gpi"
      end
    end
  end

  test do
    system "#{bin}/guppi", "--version"
  end
end
